---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app1
  template:
    metadata:
      labels:
        app: java-app1
    spec:
      containers:
        - name: java-app1-container
          image: davezworka/java_app1:0.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app1-service
spec:
  selector:
    app: java-app1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
